### ISSUE TITLE
Noticed some code you don't need 

### ISSUE THREAD

**Issue by JohnSmall** [minimul/qbo_api#44]
Just downloaded your gem and started reading through it. I noticed you've got a method

     def snake_to_camel(sym)

But ActiveSupport already has .camelize which does the job for you. 
See [ActiveSupport](http://guides.rubyonrails.org/active_support_core_extensions.html) and look at section 5.11.3 

You can remove that method.

I also noticed there's a method to parse XML, but I thought the whole idea of this gem was to get away from the old XML api. I'm only just getting in to the QBO API, is there still some XML hanging around in the latest API?

**Comment by ntippie** [comment]
I believe that is intentional, as this gem was designed to not have a dependency on ActiveSupport or any part of Rails.

If I'm recalling correctly, sometimes XML is returned for errors. Perhaps @minimul can comment. Indeed it is the old API leaking through. Interestingly, I believe we started seeing the _new_ (v4) API leaking through (check out #39).

**Comment by JohnSmall** [comment]
I saw activesupport being installed when I ran bundle and I see
Activesupport 5.1.4 is in Gemfile.lock so something is installing it.

Looks like Rspec might be installing it.

**Comment by ntippie** [comment]
You're right, it looks to me that it's `rack-oauth2`, which is a development dependency. I believe it's just for the "spin up an example" sections described in the README.

**Comment by minimul** [comment]
Yeah, some errors still come back in XML :-[

**Comment by minimul** [comment]
What @ntippie said about ActiveSupport. Closing.
